<?php


//=============================================================================
/**
 * Implements hook_menu().
 */
function statsform_menu() {
  $items = array();
  
  $items['statsform/form'] = array(
    'title' => 'Stats Form',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('statsform_page_one'),
    'access callback' => TRUE,
    'description' => 'For statsform use',
  );

  // Create a path for the AJAX request
  $items['statsform/ajax'] = array(
    'title' => 'Ajax Request',
    'page callback' => 'ajax_request_callback2',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
 
  return $items;
}


//=============================================================================
/**
 * Implements hook_page_alter().
 */
function statsform_page_alter(&$page) {
    if (arg(0) == 'statsform') {
        $page['variables'] = drupal_get_token();
        $page['#theme'] = 'hijack'; 
  }
}

//=============================================================================
/**
 * Implements hook_theme().
 */
function statsform_theme($existing, $type, $theme, $path) {
    return array(
        'hijack' => array(
#            'variables' => array('output' => 'test21'), // limited scope
            'template' => 'page--hijacked',
            'render element' => 'page',
            'path' => drupal_get_path('module', 'statsform') . '/templates',
            ),
    );
}

/**
 * Implements hook_form_alter().
 */
//function statsform_form_alter(&$form, &$form_state, $form_id) {
//    //print_r($form_id);
////    print_r("asd".$form['actions']['submit']['#attributes']['class']);
//  if ($form_id = 'statsform_page_one') {
//    //$form['actions']['submit']['#attributes']['class'][] = 'hidden';
//    //$form['actions']['submit']['#attributes'] = array('class' => 'my_class'); 
//    
//    
//    $form['actions']['submit']['#attributes']['class'][] = 'hidden';
//    $form['#attributes']['class'][] = 'hidden';
//    
//    
//    
//    
////    print_r($form['actions']['submit']['#attributes']);
//  }
//}

//=============================================================================
/**
 * Callback function for /statsform/ajax.
 */
function ajax_request_callback2() {
  if (isset($_POST['statsformToken'])) {
    if (isset($_POST['sfLogout']) && $_POST['sfLogout']) {
      // Return the Logged Out flag and exit
      $response = array(
        'message' => 'sfLoggedOut',
      );
      drupal_json_output($response);
      session_destroy();
//      drupal_goto('user');
      exit;
    } else {
      // Pass the JSON on to the WS and Return the response
      // 1. Set up the JSON here (if needed)
      $sf_json = array (
        'Submission' => 
        array (
          'unitID' => 'YRL03',
          'pointID' => '01',
          'dateTime' => '2017-09-01 14:15:00',
          'operator' => 'drickard1967',
          'timeSpent' => 5,
          'detailed' => true,
          'stats' => 
          array (
            0 => 
            array (
              'typeID' => '02',
              'modeID' => '03',
              'count' => 3,
            ),
          ),
          'Referral' => 
          array (
            'text' => 'sent to Professor X for more info',
          ),
          'Interaction' => 
          array (
            'topic' => 'linear differential equations',
            'departmentID' => 79,
            'course' => 'Math 305',
            'staffFeedback' => '',
            'patronType' => 2,
            'patronFeedback' => 'thanks',
          ),
        ),
      );
      $sf_params = json_encode($sf_json);

      // 2. Send to WS here
      $sf_url = "https://webservices-test.library.ucla.edu/pss/stats/submit";
      $sf_response = drupal_http_request($sf_url, array(
        'method' => 'PUT',
        'data' => $sf_params,
        'headers' => array('Content-Type' => 'application/json')
      ));

      // 3. Return the response
      $response = array(
//        'message' => t($_POST['statsformToken']),
//        'message' => $_POST['statsformInputDatetime'],
//        'message' => $_POST['statsformInputTime'],
//        'message' => $_POST['statsformInputLocation'],
//        'message' => $_POST['statsformInputServicePoint'],
        'message' => $_POST['statsformUserName'],
//        'message' => $_POST['statsformUserMenu'],
      );
      drupal_json_output($sf_response);
      exit;
    }
  } else {
    // Return Missing Token message
    $response = array(
      'message' => t('Error #asdf90g: Missing token.'),
    );
    drupal_json_output($response);
    exit;
  }
}




















/**
* page 1 - Choose a Library ..............................................................................................................
* page 1 - Choose a Library ..............................................................................................................
* page 1 - Choose a Library ..............................................................................................................
*/
function statsform_page_one($form, &$form_state) {
// Jump to appropriate page if necessary

    // check to see if the user is in the StatsForm group
    global $user;
    $flag = 0;

    if (in_array('administrator', $user->roles)) { // Can add more roles to this check
        $flag = 1;
        // Display page 2 if $form_state['page_num'] == 2
        if (!empty($form_state['page_num']) && $form_state['page_num'] == 2) {
            print_r('page_2');
            return statsform_page_two($form, $form_state);
        } elseif (!empty($form_state['page_num']) && $form_state['page_num'] == 3) {
            //print_r('page_3');
            return statsform_page_three($form, $form_state);
//            return statsform_mockup($form, $form_state);
        } elseif (!empty($form_state['page_num']) && $form_state['page_num'] == 4) {
            //print_r('page_4a');
            return statsform_page_four($form, $form_state);
        } elseif (!empty($form_state['page_num']) && $form_state['page_num'] == 5) {
            //print_r('page_5');
            return statsform_page_five($form, $form_state);
        } elseif (!empty($form_state['page_num']) && $form_state['page_num'] == 6) {
            //print_r('page_6');
            return statsform_page_six($form, $form_state);
        } elseif (!empty($form_state['page_num']) && $form_state['page_num'] == 7) {
            //print_r('page_7');
            return statsform_page_seven($form, $form_state);
        }

        $form['bidhide'] = array(
            '#type' => 'hidden', 
            '#default_value' => $bid
        );

        $form['html_markup1'] = array(
            '#markup' => '<div style="visibility:hidden;">'
        );

        $form['submit'] = array(
            '#type'  => 'submit',
            '#value' => t('Start'),
            '#submit' => array('statsform_page_one_handler_submit'),
        );

        return $form;

        $form['html_markup2'] = array('#markup' => '</div>');

    } else { // djc move this to the very end and indent the code between here and the end
        $form['home'] = array(
            '#type' => 'item',
            '#markup' => '
<html>
    <body>
        <h1>Stats Form App</h1>
        Please log in or contact your supervisor to gain access<br>
        Developer: Make sure that you are logged in to Drupal!
    </body>
</html>',
        );
        return $form;
    }
}


/**
* page 2 - Choose a Service Point ........................................................................................................
* page 2 - Choose a Service Point ........................................................................................................
* page 2 - Choose a Service Point ........................................................................................................
*/
function statsform_page_two($form, &$form_state) {
    $library = $form_state['values']['bidhide'];
    statsform_session_variable_set('statsform', 'libraryName', $library);
    statsform_session_variable_get('statsform', 'libraryName');

    if ($library == 'POWELL'){
        statsform_session_variable_set('statsform', 'pos1', 'Circulation Desk: second floor counter');
        statsform_session_variable_set('statsform', 'pos2', 'Reference Desk');
        statsform_session_variable_set('statsform', 'pos3', 'Information Desk');
        statsform_session_variable_set('statsform', 'pos4', 'Off-Desk');
        statsform_session_variable_set('statsform', 'pos5', 'Circulation Desk: entrance foyer');
        statsform_session_variable_set('statsform', 'pos6', 'Rovers');
    }
    if ($library == 'YRL'){
        statsform_session_variable_set('statsform', 'pos1', '1Circulation Desk');
        statsform_session_variable_set('statsform', 'pos2', 'A Level Service Desk');
        statsform_session_variable_set('statsform', 'pos3', 'Information Desk');
        statsform_session_variable_set('statsform', 'pos4', 'Cashier Window');
        statsform_session_variable_set('statsform', 'pos5', 'Phone Answering Station');
        statsform_session_variable_set('statsform', 'pos6', '');
    }
    if ($library == 'BIOMEDICAL'){
        statsform_session_variable_set('statsform', 'pos1', 'Circulation Desk');
        statsform_session_variable_set('statsform', 'pos2', 'Reference Desk');
        statsform_session_variable_set('statsform', 'pos3', 'Information Desk');
        statsform_session_variable_set('statsform', 'pos4', 'Off-Desk');
        statsform_session_variable_set('statsform', 'pos5', '');
        statsform_session_variable_set('statsform', 'pos6', '');
    }
    if ($library == 'ARTS'){
        statsform_session_variable_set('statsform', 'pos1', 'Circulation Desk');
        statsform_session_variable_set('statsform', 'pos2', 'Reference Desk');
        statsform_session_variable_set('statsform', 'pos3', 'Off Desk');
        statsform_session_variable_set('statsform', 'pos4', '');
        statsform_session_variable_set('statsform', 'pos5', '');
        statsform_session_variable_set('statsform', 'pos6', '');
    }
    if ($library == 'MUSIC'){
        statsform_session_variable_set('statsform', 'pos1', 'Circulation Desk');
        statsform_session_variable_set('statsform', 'pos2', 'Reference Desk');
        statsform_session_variable_set('statsform', 'pos3', 'Off Desk');
        statsform_session_variable_set('statsform', 'pos4', '');
        statsform_session_variable_set('statsform', 'pos5', '');
        statsform_session_variable_set('statsform', 'pos6', '');
    }

    // Jump to appropriate page if necessary
    // check to see if the user is in the StatsForm group
    global $user;
    $flag = 0;

    if (in_array('administrator', $user->roles)) { // Can add more roles to this check
        $flag = 1;
    
        $form['home2'] = array(
            '#type' => 'item',
            '#markup' => '
<html>
    <head>
        <title>Stats Redesign Project - 2</title>

        <!-- Semantic UI -->
        <link rel="stylesheet" type="text/css" href="../assets/includes/semantic.min.css">
        <script type="text/javascript" src="../assets/includes/semantic.min.js"></script>

        <!-- JQuery -->
        <script type="text/javascript" src="../assets/includes/jquery.min.js"></script>

        <!-- Customization -->
        <link rel="stylesheet" type="text/css" href="../css/stylesheet.css" />
        <!-- IScroll Link here -->
        <script type="text/javascript" src="../css/stylesheet.css"></script>
    
        <script>
            function myfunction1() {
                document.getElementsByName("bidhide3")[0].value = "circ";
                tt = document.getElementsByName("bidhide3")[0].value;
                console.log("iuyiuy");
                document.getElementById("statsform-page-one").submit();
            }
            function myfunction2() {
                document.getElementsByName("bidhide")[0].value =  "aLevel";
                document.getElementById("statsform-page-two").submit();
            }
            function myfunction3() {
                document.getElementsByName("bidhide")[0].value =  "info";
                document.getElementById("statsform-page-two").submit();
            }
            function myfunction4() {
                document.getElementsByName("bidhide")[0].value = "cashier";
                document.getElementById("statsform-page-two").submit();
            }
            function myfunction5() {
                document.getElementsByName("bidhide")[0].value = "phone";
                document.getElementById("statsform-page-two").submit();
            }
        </script>
    </head>
    <body>
        <!-- Menu -->
        <div class="ui secondary inverted menu">
            <div class="ui huge breadcrumb">
                <div class="section" >
                    <a class="item" href="/statsform/form">
                        Home
                    </a>
                </div>
                <i class="right chevron icon divider"></i>
                <div class="active section">
                    <a class="item">'.t(ucfirst(statsform_session_variable_get('statsform', 'libraryName')).'</a>
                </div>
            </div>
            <div class="right menu">
                <a class="item">
                    Login
                </a>
            </div>
        </div>')

        );

        $form['bidhide3'] = array(
            '#type' => 'hidden', 
            '#default_value' => 'zzz',
        );

    $form['pos1'] = array(
        '#type' => 'item',
        '#prefix' => '<div class="ui equal width center aligned grid">
        <a href="#" class="eight wide column" onclick="myfunction1()" id="YRL"> <div class="verticalalign">',
        '#suffix' => '</div></a></div',
        '#markup' => t(ucfirst(statsform_session_variable_get('statsform', 'pos1')).'')
    );
    $form['pos2'] = array(
        '#type' => 'item',
        '#prefix' => '<div class="ui equal width center aligned grid"><a href = "mockup"class="eight wide column" id="sec2"> <div class="verticalalign">',
        '#suffix' => '</div></a></div',
        '#markup' => t(ucfirst(statsform_session_variable_get('statsform', 'pos2')).'')
    );
    $form['pos3'] = array(
        '#type' => 'item',
        '#prefix' => '<div class="ui equal width center aligned grid"><a href = "mockup"class="eight wide column" id="sec3"> <div class="verticalalign">',
        '#suffix' => '</div></a></div',
        '#markup' => t(ucfirst(statsform_session_variable_get('statsform', 'pos3')).'')
    );
    $form['pos4'] = array(
        '#type' => 'item',
        '#prefix' => '<div class="ui equal width center aligned grid"><a href = "mockup"class="eight wide column" id="sec4"> <div class="verticalalign">',
        '#suffix' => '</div></a></div',
        '#markup' => t(ucfirst(statsform_session_variable_get('statsform', 'pos4')).'')
    );
    $form['pos5'] = array(
        '#type' => 'item',
        '#prefix' => '<div class="ui equal width center aligned grid"><a href = "mockup"class="eight wide column" id="sec5"> <div class="verticalalign">',
        '#suffix' => '</div></a></div',
        '#markup' => t(ucfirst(statsform_session_variable_get('statsform', 'pos5')).'')
    );
    $form['pos6'] = array(
        '#type' => 'item',
        '#prefix' => '<div class="ui equal width center aligned grid"><a href = "mockup"class="eight wide column" id="sec6"> <div class="verticalalign">',
        '#suffix' => '</div></a></div',
        '#markup' => t(ucfirst(statsform_session_variable_get('statsform', 'pos6')).'')
//        '#markup' => t(ucfirst(statsform_session_variable_get('statsform', 'pos6')).'</div>')
    );

        $form['html_markup1'] = array(
            '#markup' => '<div style="visibility:hidden;">',
        );

        $form['submit'] = array(
            '#type'  => 'submit',
            '#value' => t('Start'),
            '#submit' => array('statsform_page_two_handler_submit'),
        );

        return $form;

        $form['html_markup2'] = array('#markup' => '</div>');

    } else { // djc move this to the very end and indent the code between here and the end
        $form['home'] = array(
            '#type' => 'item',
            '#markup' => '
<html>
    <body>
        <h1>Stats Form App</h1>
        Please log in or contact your supervisor to gain access<br>
        Developer: Make sure that you are logged in to Drupal!
    </body>
</html>',
        );
        return $form;
    }
}


/**
* page 3 - Simple Page ...................................................................................................................
* page 3 - Simple Page ...................................................................................................................
* page 3 - Simple Page ...................................................................................................................
*/
function statsform_page_three($form, &$form_state) {
    $library = $form_state['values']['bidhide'];
    statsform_session_variable_set('statsform', 'libraryName', $library);
    statsform_session_variable_get('statsform', 'libraryName');

    // check to see if the user is in the StatsForm group
    global $user;
    $flag = 0;

    if (in_array('administrator', $user->roles)) { // Can add more roles to this check
        $flag = 1;
    
        $form['home3'] = array(
            '#type' => 'item',
            '#markup' => '
<html>
<head>
    <title>Stats Redesign Project - 3</title>

    <!-- Include meta tag to ensure proper rendering and touch zooming -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Include jQuery Mobile stylesheets -->
    <link rel="stylesheet" href="https://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.css">

    <!-- Include the jQuery library -->
    <script src="https://code.jquery.com/jquery-1.11.3.min.js"></script>

    <!-- Include the jQuery Mobile library -->
    <script src="https://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.js"></script>

    <!-- Semantic UI -->
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/1.11.8/semantic.min.css?v=1">
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/1.11.8/semantic.min.js"></script>
    <link rel="stylesheet" href="../assets/includes/calendar/dist/calendar.min.css">
    <script type="text/javascript" src="../assets/includes/calendar/dist/calendar.min.js"></script>
    <script scr="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.4/components/accordion.js"></script>


    <!-- Customization -->
    <link rel="stylesheet" type="text/css" href="../assets/includes/custom.accordion.css?v=1" />
    <!-- IScroll Link here -->
    <script type="text/javascript" src="../assets/includes/custom.accordion.js?v=1"></script>

        <script>
            function myfunction3a() {
alert("mnnb");
                document.getElementsByName("bidhide3")[0].value = "circ";
                tt = document.getElementsByName("bidhide3")[0].value;
                console.log("iuyiuy");
                document.getElementById("statsform-page-one").submit();
            }
            function myfunction2() {
                document.getElementsByName("bidhide")[0].value =  "aLevel";
                document.getElementById("statsform-page-two").submit();
            }
            function myfunction3() {
                document.getElementsByName("bidhide")[0].value =  "info";
                document.getElementById("statsform-page-two").submit();
            }
            function myfunction4() {
                document.getElementsByName("bidhide")[0].value = "cashier";
                document.getElementById("statsform-page-two").submit();
            }
            function myfunction5() {
                document.getElementsByName("bidhide")[0].value = "phone";
                document.getElementById("statsform-page-two").submit();
            }
        </script>

</head>
<body>

    <div class="ui secondary inverted menu">
        <div class="ui huge breadcrumb">
            <div class="section" >
                <a class="item" href="index.html" rel="external" data-ajax="false">
                    Home
                </a>
            </div>
            <i class="right chevron icon divider"></i>
            <div class="section">
                <a class="item" href="../references.html" rel="external" data-ajax="false">
                    Specific Library
                </a>
            </div>
            <i class="right chevron icon divider"></i>
            <div class="active section">
                <a class="item">
                    Stats Form
                </a>
            </div>
        </div>
        <div class="right menu">
            <a class="item">
                Login
            </a>
        </div>
    </div>

    <!-- Calendar -->
    <script>
  $( function() {
    $( "#datepicker" ).datepicker();
  } );
  </script>
    <h3>2Date only</h3>
  <div class="ui calendar" id="calendar">
    <div class="ui input left icon">
      <i class="calendar icon"></i>
      <input type="text" id="datepicker" placeholder="      Date">
    </div>
  </div>
  <br/>


    <!-- Accordion Start -->
    <div class="ui styled accordion">

        <!-- Quick Questions Section -->
        <div class="active title">
            <i class="dropdown icon"></i>
            Quick Questions
        </div>
        <div class="active content">
            <div class="ui equal width aligned grid">
                <div class="eight wide column"> 
                    <div class="ui fluid card withCount">
                        <div class="content"> 
                            <div class="ui inverted segment left floated" id="directions"> 
                                <div class="ui tiny inverted statistics left floated"> 
                                    <div class="statistic">
                                        <div class="value"> 0 
                                        </div> 
                                        <div class="label"> Count </div>
                                    </div>
                                </div>
                            </div>
                            <img class="ui tiny image left floated" src="../../img/directions.png"> 
                            <div class="header"> Directional </div> 
                            <div class="meta"> Location or directions provided. E.G. rooms, events, contact info, etc. </div> 
                        </div>
                    </div>
                </div>
                <div class="eight wide column"> 
                    <div class="ui fluid card withCount">
                        <div class="content">
                            <div class="ui inverted segment left floated" id="lookup">
                                <div class="ui tiny inverted statistics left floated"> 
                                    <div class="statistic">
                                        <div class="value"> 0
                                        </div> 
                                        <div class="label"> Count </div>
                                    </div>
                                </div>
                            </div>
                            <img class="ui tiny image left floated" src="../../img/lookup.png"> 
                            <div class="header"> Look Up Known Item </div>
                            <div class="meta"> Find call numbers, books, articles, locations, etc. for known items requested by patron. </div>
                        </div> 
                    </div>

                </div>
                <div class="eight wide column"> 
                    <div class="ui fluid card withCount">
                        <div class="content">
                            <div class="ui inverted segment left floated" id="policy">
                                <div class="ui tiny inverted statistics left floated"> 
                                    <div class="statistic">
                                        <div class="value"> 0
                                        </div> 
                                        <div class="label"> Count </div>
                                    </div>
                                </div>
                            </div>
                            <img class="ui tiny image left floated" src="../../img/policy.png"> 
                            <div class="header"> Policy & Operations</div>
                            <div class="meta"> Hours, access privileges, borrowing, reservations, other policies. </div>
                        </div> 
                    </div>
                </div>
                <div class="eight wide column"> 
                    <div class="ui fluid card withCount">
                        <div class="content">
                            <div class="ui inverted segment left floated" id="research">
                                <div class="ui tiny inverted statistics left floated"> 
                                    <div class="statistic">
                                        <div class="value"> 0
                                        </div> 
                                        <div class="label"> Count </div>
                                    </div>
                                </div>
                            </div>
                            <img class="ui tiny image left floated" src="../../img/research.png">
                            <div class="header"> Referral </div>
                            <div class="meta"> Referral to advance research support, library location, campus support, etc. </div>
                        </div> 
                    </div>
                </div>
                <div class="eight wide column"> 
                    <div class="ui fluid card withCount">
                        <div class="content">
                            <div class="ui inverted segment left floated" id="technical">
                                <div class="ui tiny inverted statistics left floated"> 
                                    <div class="statistic">
                                        <div class="value"> 0
                                        </div> 
                                        <div class="label"> Count </div>
                                    </div>
                                </div>
                            </div>
                            <img class="ui tiny image left floated" src="../../img/technical.png"> 
                            <div class="header"> Technical Assistance </div>
                            <div class="meta"> Help with printers, computers, software, scanners, etc. </div>
                        </div> 
                    </div>
                </div>
                <div class="eight wide column"> 
                    <div class="ui fluid card ">

<button style = "height: 120px" class="ui button" onclick="myfunction3a()" id="YRL"> <h1 style = "font-size:70px"> SUBMIT </h1> </button>

                    </div>
                </div>

            </div>
        </div>

        <!-- Referral Section -->
        <div class="title">
            <i class="dropdown icon"></i>
            Research Assistance
        </div>
        <div class="content">
            <div class="ui equal width aligned grid">
                <div class="eight wide column">
                    <div class="ui fluid card">
                        <div class="content">
                            <img class="ui tiny image left floated" src="../../img/research.png"> 
                            <div class="header"> Research Assistance </div>
                            <div class="meta"> Help patron with research strategy, advice, overview of resources (drop-in). </div>
                        </div> 
                    </div>
                </div>
                <div class="eight wide column">
                    <div class="ui fluid card">
                        <div class="content">
                            <img class="ui tiny image left floated" src="../../img/technical.png"> 
                            <div class="header"> Technical Assistance </div>
                            <div class="meta"> Help with printers, computers, software, scanners, etc. </div>
                        </div> 
                    </div>
                </div>
                <div class="eight wide column">
                    <div class="ui fluid card">
                        <div class="content">
                            <img class="ui tiny image left floated" src="../../img/lookup.png"> 
                            <div class="header"> Look up Known Item </div>
                            <div class="meta"> Find call numbers, books, articles, locations, etc. for known items requested by patron. </div>
                        </div> 
                    </div>
                </div>
                <div class="eight wide column">
                    <div class="ui fluid card">
                        <div class="content">
                            <img class="ui tiny image left floated" src="../../img/directions.png"> 
                            <div class="header"> Directional </div>
                            <div class="meta"> Location or directions provided e.g. rooms, events, contact information, etc. </div>
                        </div> 
                    </div>
                </div>
                <div class="eight wide column">
                    <div class="ui fluid card">
                        <div class="content">
                            <img class="ui tiny image left floated" src="../../img/policy.png"> 
                            <div class="header"> Policy & Operations </div>
                            <div class="meta"> Hours, access privileges, borrowing, space reservations, other policies. </div>
                        </div> 
                    </div>
                </div>

                <div class="eight wide column">
                    <form class="ui form">
                        <div class="field">
                            <label>
                                Question Topic
                            </label>
                            <input type="text" name="topic" placeholder="Add topic here." height="200">
                        </div>
                        <div class="grouped fields">
                            <label for="referral">Referral?</label>
                            <div class="field">
                                <div class="ui radio checkbox">
                                    <input type="radio" name="referral" tabindex="0" class="hidden">
                                    <label>Yes</label>
                                </div>
                            </div>
                            <div class="field">
                                <div class="ui radio checkbox">
                                    <input type="radio" name="referral" tabindex="0" class="hidden">
                                    <label>No</label>
                                </div>
                            </div>
                        </div>
                        <div class="field">
                            <label>
                                Department / Unit
                            </label>
                            <div class="ui selection dropdown">
                                <input type="hidden" name="department">
                                <i class="dropdown icon"></i>
                                <div class="default text">
                                    Choose your department
                                </div>
                                <div class="menu">
                                    <div class="item" data-value="none">N/A</div>
                                    <div class="item" data-value="linguistics">Linguistics</div>
                                    <div class="item" data-value="cs">Computer Science</div>
                                    <div class="item" data-value="commstudies">Communications</div>
                                    <div class="item" data-value="arts">Fine Arts</div>
                                </div>
                            </div>
                        </div>
                        <div class="field">
                            <label>Course / Section</label>
                            <input type="text" name="course" placeholder="CRS###/SEC###">
                        </div>
                    </form>
                </div>
            </div>
             <div class="ui equal width aligned grid">
                <div class="eight wide column">
                    <div class="ui equal width aligned grid">
                        <div class="four wide column">
                            <div class="ui inverted segment">
                                <div class="ui tiny inverted statistics">
                                    <div class="statistic">
                                        <div class="value">
                                            0
                                        </div>
                                        <div class="label">
                                            People
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="four wide column">
                            <div class="ui inverted segment">
                                <div class="ui tiny inverted statistics">
                                    <div class="statistic">
                                        <div class="value">
                                            0
                                        </div>
                                        <div class="label">
                                            Minutes
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="ui form">
                          <div class="inline fields">
                            <label>How did you help the patron?</label>
                            <div class="field">
                              <div class="ui radio checkbox">
                                <input type="radio" name="frequency" checked="checked">
                                <label>In-Person</label>
                            </div>
                        </div>
                        <div class="field">
                          <div class="ui radio checkbox">
                            <input type="radio" name="frequency">
                            <label>E-mail</label>
                        </div>
                    </div>
                    <div class="field">
                      <div class="ui radio checkbox">
                        <input type="radio" name="frequency">
                        <label>Telephone</label>
                    </div>
                </div>
            </div>
        </div>
        <div class="eight wide column">
         <form class="ui form">
            <div class="grouped fields">
                <label for="status" style = "font-size: 30px">Patron Status</label>
                <div class="field">
                    <div class="ui radio checkbox">
                        <input type="radio" name="status" tabindex="0" checked="" class="hidden">
                        <label>Unknown</label>
                    </div>
                </div>
                <div class="field">
                    <div class="ui radio checkbox">
                        <input type="radio" name="status" tabindex="0" class="hidden">
                        <label>UCLA undergrad</label>
                    </div>
                </div>
                <div class="field">
                    <div class="ui radio checkbox">
                        <input type="radio" name="status" tabindex="0" class="hidden">
                        <label>UCLA graduate student</label>
                    </div>
                </div>
                <div class="field">
                    <div class="ui radio checkbox">
                        <input type="radio" name="status" tabindex="0" class="hidden">
                        <label>UCLA faculty</label>
                    </div>
                </div>
                <div class="field">
                    <div class="ui radio checkbox">
                        <input type="radio" name="status" tabindex="0" class="hidden">
                        <label>UCLA researcher/other</label>
                    </div>
                </div>
                <div class="field">
                    <div class="ui radio checkbox">
                        <input type="radio" name="status" tabindex="0" class="hidden">
                        <label>UCLA alumnus/a</label>
                    </div>
                </div>
                <div class="field">
                    <div class="ui radio checkbox">
                        <input type="radio" name="status" tabindex="0" class="hidden">
                        <label>non-UCLA</label>
                    </div>
                </div>
            </div>
        </form>
    </div>

</div>
</div>

<!--<div class="eight wide column">
    <form class="ui form">
        <div class="field">
            <label>
                Question Topic
            </label>
            <input type="text" name="topic" placeholder="Add topic here." height="200">
        </div>
        <div class="grouped fields">
            <label for="referral">Referral?</label>
            <div class="field">
                <div class="ui radio checkbox">
                    <input type="radio" name="referral" tabindex="0" class="hidden">
                    <label>Yes</label>
                </div>
            </div>
            <div class="field">
                <div class="ui radio checkbox">
                    <input type="radio" name="referral" tabindex="0" class="hidden">
                    <label>No</label>
                </div>
            </div>
        </div>
        <div class="field">
            <label>
                Department / Unit
            </label>
            <div class="ui selection dropdown">
                <input type="hidden" name="department">
                <i class="dropdown icon"></i>
                <div class="default text">
                    Choose your department
                </div>
                <div class="menu">
                    <div class="item" data-value="none">N/A</div>
                    <div class="item" data-value="linguistics">Linguistics</div>
                    <div class="item" data-value="cs">Computer Science</div>
                    <div class="item" data-value="commstudies">Communications</div>
                    <div class="item" data-value="arts">Fine Arts</div>
                </div>
            </div>
        </div>
        <div class="field">
            <label>Course / Section</label>
            <input type="text" name="course" placeholder="CRS###/SEC###">
        </div>
    </form>
</div> 
</div>
</div> !-->

<!-- Directions Modal -->
<div class="ui modal" id="directions-modal">
    <div class="content">
        <div class="header">
            <h1>
                Edit content for Directions
            </h1>
            <div class="ui massive form">
                <div class="field">
                    <label>
                        New count:
                    </label>
                    <input placeholder="E.G.: 42" type="number" min="0" inputmode="numberic" pattern="[0-9]*" id="new-directions-count">
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Lookup Modal -->
<div class="ui modal" id="lookup-modal">
    <div class="content">
        <div class="header">
            <h1>
                Edit content for Lookup
            </h1>
            <div class="ui massive form">
                <div class="field">
                    <label>
                        New count:
                    </label>
                    <input placeholder="E.G.: 42" type="number" min="0" inputmode="numberic" pattern="[0-9]*" id="new-lookup-count">
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Policy Modal -->
<div class="ui modal" id="policy-modal">
    <div class="content">
        <div class="header">
            <h1>
                Edit content for Policy
            </h1>
            <div class="ui massive form">
                <div class="field">
                    <label>
                        New count:
                    </label>
                    <input placeholder="E.G.: 42" type="number" min="0" inputmode="numberic" pattern="[0-9]*" id="new-policy-count">
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Research Modal -->
<div class="ui modal" id="research-modal">
    <div class="content">
        <div class="header">Research Assistance
            <h1>
                Edit content for Research Assistance
            </h1>
            <div class="ui massive form">
                <div class="field">
                    <label>
                        New count:
                    </label>
                    <input placeholder="E.G.: 42" type="number" min="0" inputmode="numberic" pattern="[0-9]*" id="new-research-count">
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Technical Modal -->
<div class="ui modal" id="technical-modal">
    <div class="content">
        <div class="header">
            <h1>
                Edit content for Technical Assistance
            </h1>
            <div class="ui massive form">
                <div class="field">
                    <label>
                        New count:
                    </label>
                    <input placeholder="E.G.: 42" type="number" min="0" inputmode="numberic" pattern="[0-9]*" id="new-technical-count">
                </div>
            </div>
        </div>
    </div>
</div>

</div>

</body>
</html>
',
        );

        $form['bidhide3'] = array(
            '#type' => 'hidden', 
            '#default_value' => 'zzz',
        );

        $form['html_markup1'] = array(
            '#markup' => '<div style="visibility:hidden;">',
        );

        $form['submit'] = array(
            '#type'  => 'submit',
            '#value' => t('Start'),
            '#submit' => array('statsform_page_three_handler_submit'),
        );

        return $form;

        $form['html_markup2'] = array('#markup' => '</div>');

    } else { // djc move this to the very end and indent the code between here and the end
        $form['home'] = array(
            '#type' => 'item',
            '#markup' => '
<html>
    <body>
        <h1>Stats Form App</h1>
        Please log in or contact your supervisor to gain access<br>
        Developer: Make sure that you are logged in to Drupal!
    </body>
</html>',
        );
        return $form;
    }
}



/**
 * Page 1 submit handler.
 * Page 1 submit handler.
 * Page 1 submit handler.
 *
 * Save the vals from page one for a later final submit.
 */
  // Values are saved for each page.
  // to carry forward to subsequent pages in the form.
  // The Forms API rebuilds the form.
function statsform_page_one_handler_submit($form, &$form_state) {
  $form_state['page_values'][1] = $form_state['values'];

  // set page num if it does not yet exist, ie this is the first pass
  if (empty($form_state['page_num'])) { $form_state['page_num'] = 1; } 

  // go forward to page 2
  $form_state['page_num'] = 2;

  $form_state['rebuild'] = TRUE;
}



/**
 * Page 2 submit handler.
 * Page 2 submit handler.
 * Page 2 submit handler.
 *
 * Save the vals from page one for a later final submit.
 */
  // Values are saved for each page.
  // to carry forward to subsequent pages in the form.
  // The Forms API rebuilds the form.
function statsform_page_two_handler_submit($form, &$form_state) {
  $form_state['page_values'][1] = $form_state['values'];

  // set page num if it does not yet exist, ie this is the first pass
  if (empty($form_state['page_num'])) { $form_state['page_num'] = 2; } 

  // go forward to page 3
  $form_state['page_num'] = 3;

  $form_state['rebuild'] = TRUE;
}



/**
 * Page 3 submit handler.
 * Page 3 submit handler.
 * Page 3 submit handler.
 *
 * Save the vals from page one for a later final submit.
 */
  // Values are saved for each page.
  // to carry forward to subsequent pages in the form.
  // The Forms API rebuilds the form.
function statsform_page_three_handler_submit($form, &$form_state) {
  $form_state['page_values'][1] = $form_state['values'];
krumo("dfghdfgh");
  // set page num if it does not yet exist, ie this is the first pass
  if (empty($form_state['page_num'])) { $form_state['page_num'] = 3; }

  // go forward to page 4
  $form_state['page_num'] = 1;

  $form_state['rebuild'] = TRUE;
}



/**
 * session variable functions
 * session variable functions
 * session variable functions
 *
 * Based on code from Peter Moulding http://petermoulding.com/session_variable
 */
function statsform_session_variable_check_session()
	{
	return session_id() != '';
	}

function statsform_session_variable_check_module($module4rc)
	{
	$module_safe4rc = statsform_session_variable_safe($module4rc);
	if($module_safe4rc !== $module4rc or isset($_SESSION[$module4rc]))
		{
		return false;
		}
	return true;
	}

function statsform_session_variable_delete($module4rc, $name4rc)
	{
	if(statsform_session_variable_is($module4rc, $name4rc))
		{
		$module4rc = statsform_session_variable_safe($module4rc);
		$name4rc = statsform_session_variable_safe($name4rc);
		unset($_SESSION[$module4rc][$name4rc]);
		if(!count($_SESSION[$module4rc]))
			{
			unset($_SESSION[$module4rc]);
			}
		return true;
		}
	return false;
	}

function statsform_session_variable_is($module4rc, $name4rc)
	{
	$module4rc = statsform_session_variable_safe($module4rc);
	$name4rc = statsform_session_variable_safe($name4rc);
	return (isset($_SESSION[$module4rc]) and isset($_SESSION[$module4rc][$name4rc]));
	}

function statsform_session_variable_get($module4rc, $name4rc, $default_value = '')
	{
	if(rc_session_variable_is($module4rc, $name4rc))
		{
		$module4rc = statsform_session_variable_safe($module4rc);
		$name4rc = statsform_session_variable_safe($name4rc);
		return $_SESSION[$module4rc][$name4rc];
		}
	return $default_value;
	}

function statsform_session_variable_set($module4rc, $name4rc, $value = '')
	{
	$module4rc = statsform_session_variable_safe($module4rc);
	$name4rc = statsform_session_variable_safe($name4rc);
	$_SESSION[$module4rc][$name4rc] = $value;
	}

/*
Is the module name or the variable name safe for use as an entry in the session?
This function returns a safe version of the name.
*/
function statsform_session_variable_safe($name4rc = '')
	{
	return htmlentities($name4rc);
	}
